version: '3.8'

services:
  # Build service for service-a
  service-a-build:
    image: node:23-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "cd /app && 
             apt-get update && apt-get install -y python3 build-essential &&
             rm -rf /var/lib/apt/lists/* &&
             cd /app/apps/service-a &&
             npm install &&
             npm run build"

  # Build service for service-b
  service-b-build:
    image: node:23-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "cd /app && 
             apt-get update && apt-get install -y python3 build-essential &&
             rm -rf /var/lib/apt/lists/* &&
             cd /app/apps/service-b &&
             npm install &&
             npm run build"
